function xReturn = getAphiaNameByID(obj,AphiaID)
%getAphiaNameByID(obj,AphiaID)
%
%   <strong>Get the name for a given AphiaID</strong>.
%   
%     Input:
%       AphiaID = (int)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   AphiaID, ...
   };
names = { ...
   'AphiaID', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://aphia/v1.0/AphiaName', ...
    'getAphiaNameByID', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'getAphiaNameByID', ...
    soapMessage);
xReturn = parseSoapResponse(response);
